### ISSUE TITLE
How to extend to other 6-DoF Arm 

### ISSUE THREAD

**Issue by GayStarc** [UT-Austin-RobIn/telemoma#3]
Hi! Your work is so great. But I have some questions about how to extend to other 6-DoF arm real robot. 
Why you don't try Fetch Robot in real world ? Is it because that such structure of robot arm is hard to mobile manipulate? 
I now want to try to mobile manipulate a robot similar to Fetch Robot. 
Thank you for your assistance in advance!

**Comment by ShivinDass** [comment]
Hello @GayStarc,
We currently don't have support for Fetch Robot in real world because we didn't have access to one but it's easy to extend Telemoma to your own robot. 

To set up Telemoma on your own robot, the easiest way would be to create a gym-like wrapper around the functionalities of your robot (refer to [HSRGym](https://github.com/UT-Austin-RobIn/telemoma/blob/telemoma-real/telemoma/robot_interface/hsr/hsr_gym.py) for a real world example and [FetchEnv](https://github.com/UT-Austin-RobIn/telemoma/blob/telemoma-real/telemoma/robot_interface/igibson/fetch.py#L31) for a sim example).

Specifically, you would need to define,
1. A function that returns the base, torso and end-effector poses as observations (see [here](https://github.com/UT-Austin-RobIn/telemoma/blob/2433c36f729c001ea7db1e805d81c3fbe7b95e8f/telemoma/robot_interface/hsr/hsr_gym.py#L106) for an example on a real HSR)
2. A function that receives the actions from the Telemoma's human-interfaces and sends appropriate controls to the robot's joints to take those actions (see [here](https://github.com/UT-Austin-RobIn/telemoma/blob/2433c36f729c001ea7db1e805d81c3fbe7b95e8f/telemoma/robot_interface/hsr/hsr_gym.py#L128) for an example on a real HSR). The actions for the base are linear and angular velocities and for the end-effector are 6DoF cartesian deltas.

There is also some more info provided [here](https://github.com/UT-Austin-RobIn/telemoma/blob/telemoma-real/telemoma/robot_interface/README.md#setting-up-telemoma-with-your-own-robot) about the observation and action spaces to help set up telemoma on your own robot.

Let me know if you get stuck or have any other questions. If you end up setting Telemoma up on your fetch, feel free to open a PR and we would be happy to incorporate it into Telemoma for anyone looking to work with Fetch in the future.
